spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://42.192.99.152:3306/permission?connectTimeout=3000&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
    ## 连接池配置
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionInitSqls: set names utf8mb4;
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: -1
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        loginUsername: admin
        loginPassword: 123456

  mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
      db-config:
        logic-delete-value: 0 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    type-aliases-package: com.platform.oauth.mapper
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
