spring:
  boot:
    admin:
      client:
        url: http://localhost:5204
        instance:
          prefer-ip: true
        register-once: true
#需要暴露监控端口给spring boot admin server访问
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

