spring:
  profiles:
    active: admin,gateway,mysql,sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.99.152:8848
  application:
    name: PLATFORM-GATEWAY
server:
  port: 5201
debug: true
customer:
  feign:
    client-id: Admin
    client-secret: Admin
logging:
  file:
    path: /root/serviceLogs/